version: '3'

# service description
services:

  # cloudflare tunnel
  netdata:
    image: netdata/netdata:edge
    container_name: netdata
    hostname: ${NETDATA_CONT_HOSTNAME}
    restart: unless-stopped
    ports:
      - 19999:19999
    cap_add:
      - SYS_PTRACE
    security_opt:
      - apparmor:unconfined
    volumes:
      - netdataconfig:/etc/netdata
      - netdatalib:/var/lib/netdata
      - netdatacache:/var/cache/netdata
      - /etc/passwd:/host/etc/passwd:ro
      - /etc/group:/host/etc/group:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /etc/os-release:/host/etc/os-release:ro
    environment:
      - NETDATA_CLAIM_TOKEN=${NETDATA_CONT_CLAIM_TOKEN}
      - NETDATA_CLAIM_URL=${NETDATA_CONT_CLAIM_URL}
      - NETDATA_CLAIM_ROOMS=${NETDATA_CONT_CLAIM_ROOMS}
    labels:
      # enbale watchtower updates
      - "com.centurylinklabs.watchtower.enable=true"

volumes:
  netdataconfig:
  netdatalib:
  netdatacache:
